version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Run python script
      - run: pip install PyGithub --user
      - run: python3 demo.py
      - run: git version
      - run: git status
      - run: git config --global user.email "1639301503@qq.com"
      - run: git config --global user.name "jwenjian"
      - run: git add .
      - run: git commit -m "update from circle ci"
      - run: git push origin master
      - run: echo 'done'

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *" 
          filters:
            branches:
              only: test-cron-ci

    jobs:
      - build