version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      # Run python script
      - run:
        - pip install PyGithub
        - python3 demo.py
        - git version
        - git status
        - git add .
        - git commit -m "update from circle ci"
        - git push origin master
        - echo 'done'

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *" 
          filters:
            branches:
              only: test-cron-ci

    jobs:
      - build